language: node_js
branches:
  only:
    - master
    - develop
    - feature/travisci
node_js:
  - "14"
#  - "13"
#  - "12"
#  - "11"
#  - "10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends \
      autoconf \
      automake \
      bzip2 \
      dpkg-dev \
      file \
      ffmpeg \
      g++ \
      gcc \
      imagemagick \
      libbz2-dev \
      libc6-dev \
      libcurl4-openssl-dev \
      libdb-dev \
      libevent-dev \
      libffi-dev \
      libgdbm-dev \
      libglib2.0-dev \
      libgmp-dev \
      libjpeg-dev \
      libkrb5-dev \
      liblzma-dev \
      libmagickcore-dev \
      libmagickwand-dev \
      libmaxminddb-dev \
      libncurses5-dev \
      libncursesw5-dev \
      libpng-dev \
      libpq-dev \
      libreadline-dev \
      libsqlite3-dev \
      libssl-dev \
      libtool \
      libwebp-dev \
      libxml2-dev \
      libxslt-dev \
      libyaml-dev \
      make \
      patch \
      unzip \
      xz-utils \
      zlib1g-dev

install: npm install
