language: node_js
branches:
  only:
    - master
    - develop
    - feature/travisci
node_js:
  - "14"
#  - "13"
#  - "12"
#  - "11"
#  - "10"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ffmpeg build-essential make gcc g++
install: npm install
